// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/cave-dwelling/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cave-dwelling/status.get').default>>>>
    }
    '/api/character/equipment/equip': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/equipment/equip.post').default>>>>
    }
    '/api/character/equipment/unequip': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/equipment/unequip.post').default>>>>
    }
    '/api/character/skills/learn': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/skills/learn.post').default>>>>
    }
    '/api/character/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/stats.get').default>>>>
    }
    '/api/character/stats/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/stats/update.post').default>>>>
    }
    '/api/character/sync-combat-power': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/sync-combat-power.post').default>>>>
    }
    '/api/character/update-combat-power': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/character/update-combat-power.post').default>>>>
    }
    '/api/combat/fight': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/combat/fight.post').default>>>>
    }
    '/api/cultivation/auto-cultivate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cultivation/auto-cultivate.post').default>>>>
    }
    '/api/cultivation/breakthrough': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cultivation/breakthrough.post').default>>>>
    }
    '/api/cultivation/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cultivation/start.post').default>>>>
    }
    '/api/cultivation/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cultivation/status.get').default>>>>
    }
    '/api/furnace/craft': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/furnace/craft.post').default>>>>
    }
    '/api/furnace/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/furnace/status.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/inventory/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/list.get').default>>>>
    }
    '/api/player/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/[id].get').default>>>>
    }
    '/api/player/companions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/companions.get').default>>>>
    }
    '/api/player/resources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/resources.get').default>>>>
    }
    '/api/player/resources/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/resources/add.post').default>>>>
    }
    '/api/player/resources/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/resources/update.post').default>>>>
    }
    '/api/player/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/player/update.post').default>>>>
    }
    '/api/quest/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/quest/complete.post').default>>>>
    }
    '/api/quest/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/quest/list.get').default>>>>
    }
    '/api/quest/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/quest/start.post').default>>>>
    }
    '/api/quest/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/quest/stats.get').default>>>>
    }
    '/api/ranking/top-players': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ranking/top-players.get').default>>>>
    }
    '/api/shop/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shop/list.get').default>>>>
    }
    '/api/shop/purchase': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shop/purchase.post').default>>>>
    }
    '/api/spirit-beast/feed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/spirit-beast/feed.post').default>>>>
    }
    '/api/spirit-beast/hunt': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/spirit-beast/hunt.post').default>>>>
    }
    '/api/spirit-beast/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/spirit-beast/status.get').default>>>>
    }
    '/api/talent/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talent/status.get').default>>>>
    }
    '/api/talent/toggle': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talent/toggle.post').default>>>>
    }
    '/api/talent/unlock': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talent/unlock.post').default>>>>
    }
    '/api/talent/upgrade': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talent/upgrade.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}