[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --legacy-peer-deps",
  "npm rebuild"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"
