// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 3:24:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/THE SUN/Desktop/TienLoThan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/plugins/**/*.{js,ts,mjs}","C:/Users/THE SUN/Desktop/TienLoThan/composables/**/*.{js,ts,mjs}","C:/Users/THE SUN/Desktop/TienLoThan/utils/**/*.{js,ts,mjs}","C:/Users/THE SUN/Desktop/TienLoThan/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/THE SUN/Desktop/TienLoThan/app.config.{js,ts,mjs}","C:/Users/THE SUN/Desktop/TienLoThan/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;